name: Compile Thesis PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build-thesis:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          package-file: thesis/tl_packages
      - name: Check `latex` version
        run: latex --version
      - name: Compile `thesis.tex`
        run: |
          cd thesis
          latexmk thesis.tex
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          token: ${{ github.token }}
          draft: true
          files: |
            thesis/thesis.pdf
