name: Compile Thesis PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build-thesis:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: thesis/tl_packages
      - name: Check `latexmk` version
        run: latexmk --version
      - name: Compile `thesis.tex`
        run: |
          cd thesis
          latexmk thesis.tex
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          token: ${{ github.token }}
          files: |
            thesis/thesis.pdf
